# DINO-evaluation.yaml
# Configured for the Zenodo `50.zip` dataset unpacked at data/50/

mesh_mask: mesh_mask.nc

restart_files: 'restart'

output_variables:
  temperature:
    filename: DINO_1y_grid_T.nc
    term: toce
  salinity:
    filename: DINO_1y_grid_T.nc
    term: soce
  density:
    filename: DINO_1y_grid_T.nc
    term: rhop
  ssh:
    filename: DINO_1m_To_1y_grid_T.nc
    term: ssh
  velocity_u:
    filename: DINO_1y_grid_U.nc
    term: uoce
  velocity_v:
    filename: DINO_1y_grid_V.nc
    term: voce

variable_map:
  time_counter: [time]
  temperature: [toce, tn]
  velocity_u: [un, u, uoce, zonal_velocity]
  velocity_v: [vn, v, voce, meridional_velocity]
  depth: [nav_lev, deptht, depthu, depthv]
  ssh: [sshn]
  salinity: [so, sn, soce]
  density: [rhop]
