# DINO-evaluation.yaml
# Configured for the Zenodo `50.zip` dataset unpacked at data/50/

mesh_mask: mesh_mask.nc

restart_files: 'restart'

output_variables:
  temperature: DINO_1y_grid_T.nc
  salinity: DINO_1y_grid_T.nc
  density: DINO_1y_grid_T.nc
  ssh: DINO_1m_To_1y_grid_T.nc
  velocity_u: DINO_1y_grid_U.nc
  velocity_v: DINO_1y_grid_V.nc
